
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nejtnguhudgmqixenlpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lanRuZ3VodWRnbXFpeGVubHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDI1ODQsImV4cCI6MjA1MzkxODU4NH0.pDmvaPm2kHEKV8O4aErkcR1MfWbD51KrBRiTA8UBqMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
